-- =======================================================
-- PRETTY PLEASE BOUTIQUE ♡ - TABLA DE PRENDAS EN SUPABASE
-- Copiar todo este código y pegarlo en:
-- https://supabase.com/dashboard/project/jpibxoedrwalsuqfovkv/sql/new
-- Luego presionar el botón verde "RUN" (Ejecutar)
-- =======================================================

-- 1. Crear tabla de prendas
CREATE TABLE IF NOT EXISTS public.prendas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    categoria TEXT NOT NULL,
    precio NUMERIC(10, 2) NOT NULL,
    precio_regular NUMERIC(10, 2),
    badge TEXT,
    imagen TEXT NOT NULL,
    tallas JSONB DEFAULT '["S", "M", "L"]'::jsonb,
    colores JSONB DEFAULT '["#C51F3D", "#E6B8B9"]'::jsonb,
    disponible BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Habilitar Seguridad por Fila (Row Level Security)
ALTER TABLE public.prendas ENABLE ROW LEVEL SECURITY;

-- 3. Limpiar políticas previas si existieran
DROP POLICY IF EXISTS "Permitir lectura publica" ON public.prendas;
DROP POLICY IF EXISTS "Permitir insercion" ON public.prendas;
DROP POLICY IF EXISTS "Permitir actualizacion" ON public.prendas;
DROP POLICY IF EXISTS "Permitir eliminacion" ON public.prendas;

-- 4. Crear políticas para lectura pública y gestión del catálogo
CREATE POLICY "Permitir lectura publica"
    ON public.prendas
    FOR SELECT
    USING (true);

CREATE POLICY "Permitir insercion"
    ON public.prendas
    FOR INSERT
    WITH CHECK (true);

CREATE POLICY "Permitir actualizacion"
    ON public.prendas
    FOR UPDATE
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Permitir eliminacion"
    ON public.prendas
    FOR DELETE
    USING (true);

-- 5. Habilitar sincronización en tiempo real (Realtime)
ALTER PUBLICATION supabase_realtime ADD TABLE public.prendas;
